[package]
name = "llm"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version="0.11.16", features = ["blocking", "json"] }
serde = { version="1.0.160", features=["derive"] }
serde_json = { version="1.0.96" }
tokio = { version="1.27.0", features=["rt-multi-thread", "macros"] }